[
  {
    "inputs": [],
    "name": "CallFailedForUnknownReason",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "messageId",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "errorData",
        "type": "bytes"
      }
    ],
    "name": "MessageFailure",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "messageId",
        "type": "bytes32"
      }
    ],
    "name": "MessageIdAlreadyExecuted",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "fromChainId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "messageId",
        "type": "bytes32"
      }
    ],
    "name": "MessageIdExecuted",
    "type": "event"
  }
]
